# Generated by Django 5.1.3 on 2025-06-04 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('rfid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='first name')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('role', models.CharField(choices=[('master', 'мастер'), ('operator', 'оператор')], default='operator', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('condition', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='WebARM.condition')),
            ],
        ),
        migrations.CreateModel(
            name='ListChangeCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('send', models.BooleanField()),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listchange', to='WebARM.condition')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machinechange', to='WebARM.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userchange', to='WebARM.user')),
            ],
        ),
    ]
